// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class AppTopologyTransport: AppTopologyStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://apptopology.googleapis.com",
      )
    }

    public func generateDiscoveredResourcesTopology(
      request: GenerateDiscoveredResourcesTopologyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppTopologyV1.GenerateDiscoveredResourcesTopologyResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/discoveredResourcesTopology"),
              ])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):generate"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/discoveredResourcesTopology"),
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/discoveredResourcesTopology"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudAppTopologyV1.GenerateDiscoveredResourcesTopologyResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func getSchema(
      request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppTopologyV1.Schema {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/domains/"), .singleWildcard, .literal("/schema"),
              ])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/domains/"), .singleWildcard, .literal("/schema"),
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/domains/*/schema"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudAppTopologyV1.Schema.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getDomain(
      request: GetDomainRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppTopologyV1.Domain {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/domains/"), .singleWildcard,
              ])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/domains/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/domains/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudAppTopologyV1.Domain.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listDomains(
      request: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppTopologyV1.ListDomainsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/domains"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudAppTopologyV1.ListDomainsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.name as Swift.String?, matching: [.literal("projects/"), .singleWildcard])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/locations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "name",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.ListLocationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.Location.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/operations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(
            contentsOf: try encoder.encode(
              request.returnPartialSuccess, prefix: "returnPartialSuccess"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = GoogleCloudGax._RoutingMatcher.value(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ])
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):cancel"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(path: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
