// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "AppTopologyQuickstart")
public final class AppTopologyClient: Clients.AppTopologyProtocol, Sendable {
  let inner: any Clients.AppTopologyStub

  /// Creates a new `AppTopologyClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AppTopologyStub = try Clients.AppTopologyTransport(options)
    inner = Clients.AppTopologyRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AppTopologyLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Generate the topology for all resources in the given project. If the
  /// project represents an
  /// [app
  /// boundary](https://cloud.google.com/app-hub/docs/reference/rest/v1/Boundary),
  /// the topology is generated for all resources in the boundary.
  ///
  /// @Snippet(path: "AppTopology_GenerateDiscoveredResourcesTopology")
  public func generateDiscoveredResourcesTopology(
    request: GenerateDiscoveredResourcesTopologyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAppTopologyV1.GenerateDiscoveredResourcesTopologyResponse {
    try await self.inner.generateDiscoveredResourcesTopology(request: request, options: options)
  }

  /// Retrieves the schema for the specified topology domain. The schema
  /// defines the NodeTypes and EdgeTypes that are supported in
  /// GenerateDiscoveredResourcesTopology requests and responses for a given
  /// domain.
  ///
  /// @Snippet(path: "AppTopology_GetSchema")
  public func getSchema(
    request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAppTopologyV1.Schema {
    try await self.inner.getSchema(request: request, options: options)
  }

  /// Retrieves the specified topology domain.
  ///
  /// @Snippet(path: "AppTopology_GetDomain")
  public func getDomain(
    request: GetDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAppTopologyV1.Domain {
    try await self.inner.getDomain(request: request, options: options)
  }

  /// Lists the topology domains available in a specific location.
  /// Only `global` location is supported.
  ///
  /// @Snippet(path: "AppTopology_ListDomains")
  public func listDomains(
    request: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAppTopologyV1.ListDomainsResponse {
    try await self.inner.listDomains(request: request, options: options)
  }

  /// Lists the topology domains available in a specific location.
  /// Only `global` location is supported.
  ///
  /// @Snippet(path: "AppTopology_ListDomains")
  public func listDomains(
    byItem: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Domain, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppTopologyV1.ListDomainsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDomains(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "AppTopology_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "AppTopology_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "AppTopology_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppTopology_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppTopology_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppTopology_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppTopology_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppTopology_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AppTopologyClient`.
  ///
  /// To mock `AppTopologyClient` change your functions to receive
  /// `some AppTopologyProtocol` or `any AppTopologyProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AppTopologyProtocol {
    /// See `AppTopologyClient.generateDiscoveredResourcesTopology`.
    func generateDiscoveredResourcesTopology(request: GenerateDiscoveredResourcesTopologyRequest)
      async throws -> GoogleCloudAppTopologyV1.GenerateDiscoveredResourcesTopologyResponse

    /// See `AppTopologyClient.generateDiscoveredResourcesTopology`.
    func generateDiscoveredResourcesTopology(
      name: Swift.String,
      topologyDomains: [Swift.String],
    ) async throws -> GoogleCloudAppTopologyV1.GenerateDiscoveredResourcesTopologyResponse

    /// See `AppTopologyClient.getSchema`.
    func getSchema(request: GetSchemaRequest) async throws -> GoogleCloudAppTopologyV1.Schema

    /// See `AppTopologyClient.getSchema`.
    func getSchema(
      name: Swift.String,
    ) async throws -> GoogleCloudAppTopologyV1.Schema

    /// See `AppTopologyClient.getDomain`.
    func getDomain(request: GetDomainRequest) async throws -> GoogleCloudAppTopologyV1.Domain

    /// See `AppTopologyClient.getDomain`.
    func getDomain(
      name: Swift.String,
    ) async throws -> GoogleCloudAppTopologyV1.Domain

    /// See `AppTopologyClient.listDomains`.
    func listDomains(request: ListDomainsRequest) async throws
      -> GoogleCloudAppTopologyV1.ListDomainsResponse

    /// See `AppTopologyClient.listDomains`.
    func listDomains(
      byItem: ListDomainsRequest
    ) throws -> any AsyncSequence<Domain, Swift.Error>

    /// See `AppTopologyClient.listDomains`.
    func listDomains(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Domain, Swift.Error>

    /// See `AppTopologyClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `AppTopologyClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AppTopologyClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `AppTopologyClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `AppTopologyClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AppTopologyClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AppTopologyClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `AppTopologyClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `AppTopologyClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `AppTopologyClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `AppTopologyClient.generateDiscoveredResourcesTopology`.
    func generateDiscoveredResourcesTopology(
      request: GenerateDiscoveredResourcesTopologyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppTopologyV1.GenerateDiscoveredResourcesTopologyResponse

    /// See `AppTopologyClient.getSchema`.
    func getSchema(
      request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppTopologyV1.Schema

    /// See `AppTopologyClient.getDomain`.
    func getDomain(
      request: GetDomainRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppTopologyV1.Domain

    /// See `AppTopologyClient.listDomains`.
    func listDomains(
      request: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAppTopologyV1.ListDomainsResponse

    /// See `AppTopologyClient.listDomains`.
    func listDomains(
      byItem: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Domain, Swift.Error>

    /// See `AppTopologyClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `AppTopologyClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AppTopologyClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `AppTopologyClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AppTopologyClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AppTopologyClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AppTopologyClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AppTopologyProtocol {
  public func generateDiscoveredResourcesTopology(
    request: GenerateDiscoveredResourcesTopologyRequest
  ) async throws -> GoogleCloudAppTopologyV1.GenerateDiscoveredResourcesTopologyResponse {
    try await self.generateDiscoveredResourcesTopology(request: request, options: .init())
  }

  public func generateDiscoveredResourcesTopology(
    request: GenerateDiscoveredResourcesTopologyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAppTopologyV1.GenerateDiscoveredResourcesTopologyResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateDiscoveredResourcesTopology(
    name: Swift.String,
    topologyDomains: [Swift.String],
  ) async throws -> GoogleCloudAppTopologyV1.GenerateDiscoveredResourcesTopologyResponse {
    let request = GenerateDiscoveredResourcesTopologyRequest().with {
      $0.name = name
      $0.topologyDomains = topologyDomains
    }
    return try await self.generateDiscoveredResourcesTopology(request: request)
  }

  public func getSchema(request: GetSchemaRequest) async throws -> GoogleCloudAppTopologyV1.Schema {
    try await self.getSchema(request: request, options: .init())
  }

  public func getSchema(
    request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAppTopologyV1.Schema {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSchema(
    name: Swift.String,
  ) async throws -> GoogleCloudAppTopologyV1.Schema {
    let request = GetSchemaRequest().with {
      $0.name = name
    }
    return try await self.getSchema(request: request)
  }

  public func getDomain(request: GetDomainRequest) async throws -> GoogleCloudAppTopologyV1.Domain {
    try await self.getDomain(request: request, options: .init())
  }

  public func getDomain(
    request: GetDomainRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAppTopologyV1.Domain {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDomain(
    name: Swift.String,
  ) async throws -> GoogleCloudAppTopologyV1.Domain {
    let request = GetDomainRequest().with {
      $0.name = name
    }
    return try await self.getDomain(request: request)
  }

  public func listDomains(request: ListDomainsRequest) async throws
    -> GoogleCloudAppTopologyV1.ListDomainsResponse
  {
    try await self.listDomains(request: request, options: .init())
  }

  public func listDomains(
    request: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAppTopologyV1.ListDomainsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDomains(
    byItem: ListDomainsRequest
  ) throws -> any AsyncSequence<Domain, Swift.Error> {
    try self.listDomains(byItem: byItem, options: .init())
  }

  public func listDomains(
    byItem: ListDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Domain, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAppTopologyV1.ListDomainsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDomains(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Domain, Swift.Error> {
    let request = ListDomainsRequest().with {
      $0.parent = parent
    }
    return try self.listDomains(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
