// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Represents a single edge connecting two nodes in the graph.
public struct Edge: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Properties associated with the edge.
  /// Refer to https://apptopology.googleapis.com/v1/GetSchema for a detailed
  /// list of edge properties.
  public var properties: GoogleWKT.Struct? = nil

  /// The name of the source node for this edge. This is the `name` field in the
  /// Node.
  public var sourceNodeName: Swift.String = Swift.String()

  /// The name of the destination node for this edge. This is the `name` field in
  /// the Node.
  public var destinationNodeName: Swift.String = Swift.String()

  /// Labels attached to the edge. Composable, namespaced building blocks that
  /// define core attributes through associated properties. Multiple labels
  /// aggregate to fully specify the functional traits and property schema of the
  /// edge type.
  public var labels: [Swift.String] = []

  /// The context of the edge.
  public var context: EntityContext? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Edge`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Edge().with { $0.properties = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let properties = CodingKeys(stringValue: "properties")
    static let sourceNodeName = CodingKeys(stringValue: "sourceNodeName")
    static let destinationNodeName = CodingKeys(stringValue: "destinationNodeName")
    static let labels = CodingKeys(stringValue: "labels")
    static let context = CodingKeys(stringValue: "context")

    static let _knownKeys: Set<Swift.String> = [
      "properties",
      "sourceNodeName",
      "destinationNodeName",
      "labels",
      "context",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.properties = try container.decodeIfPresent(GoogleWKT.Struct.self, forKey: .properties)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceNodeName) {
      self.sourceNodeName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destinationNodeName) {
      self.destinationNodeName = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .labels) {
      self.labels = value
    }
    self.context = try container.decodeIfPresent(EntityContext.self, forKey: .context)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.properties, forKey: .properties)
    try container.encode(self.sourceNodeName, forKey: .sourceNodeName)
    try container.encode(self.destinationNodeName, forKey: .destinationNodeName)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.context, forKey: .context)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apptopology.v1.Edge"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
