// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// EdgeRule defines the connection rules for nodes in the graph.
public struct EdgeRule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Name of the connected edge type.
  public var edgeType: Swift.String = Swift.String()

  /// Specifies the source criteria for this edge rule.
  /// An edge rule must define its source either statically via a specific
  /// node type, or dynamically via a group of nodes that match given
  /// constraints.
  ///
  /// This takes precedence over the `source_node_type` field.
  public var sourceNode: OneOf_SourceNode? = nil

  /// Specifies the destination criteria for this edge rule.
  /// An edge rule must define its destination either statically via a specific
  /// node type, or dynamically via a group of nodes that match given
  /// constraints.
  ///
  /// This takes precedence over the `destination_node_type` field.
  public var destinationNode: OneOf_DestinationNode? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EdgeRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EdgeRule().with { $0.srcNodeType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let srcNodeType = CodingKeys(stringValue: "srcNodeType")
    static let srcNodeGroup = CodingKeys(stringValue: "srcNodeGroup")
    static let destNodeType = CodingKeys(stringValue: "destNodeType")
    static let destNodeGroup = CodingKeys(stringValue: "destNodeGroup")
    static let edgeType = CodingKeys(stringValue: "edgeType")

    static let _knownKeys: Set<Swift.String> = [
      "srcNodeType",
      "srcNodeGroup",
      "destNodeType",
      "destNodeGroup",
      "edgeType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .edgeType) {
      self.edgeType = value
    }

    var sourceNode: OneOf_SourceNode? = nil
    let sourceNodeCheckAndSet = {
      if sourceNode != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sourceNode'"))
      }
      sourceNode = $0
    }
    if let srcNodeType = try container.decodeIfPresent(Swift.String.self, forKey: .srcNodeType) {
      try sourceNodeCheckAndSet(.srcNodeType(srcNodeType))
    }
    if let srcNodeGroup = try container.decodeIfPresent(NodeGroup?.self, forKey: .srcNodeGroup) {
      try sourceNodeCheckAndSet(.srcNodeGroup(srcNodeGroup))
    }
    self.sourceNode = sourceNode

    var destinationNode: OneOf_DestinationNode? = nil
    let destinationNodeCheckAndSet = {
      if destinationNode != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destinationNode'"))
      }
      destinationNode = $0
    }
    if let destNodeType = try container.decodeIfPresent(Swift.String.self, forKey: .destNodeType) {
      try destinationNodeCheckAndSet(.destNodeType(destNodeType))
    }
    if let destNodeGroup = try container.decodeIfPresent(NodeGroup?.self, forKey: .destNodeGroup) {
      try destinationNodeCheckAndSet(.destNodeGroup(destNodeGroup))
    }
    self.destinationNode = destinationNode
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.edgeType, forKey: .edgeType)

    if let choice = self.sourceNode {
      switch choice {
      case .srcNodeType(let value):
        try container.encode(value, forKey: .srcNodeType)
      case .srcNodeGroup(let value):
        try container.encode(value, forKey: .srcNodeGroup)
      }
    }

    if let choice = self.destinationNode {
      switch choice {
      case .destNodeType(let value):
        try container.encode(value, forKey: .destNodeType)
      case .destNodeGroup(let value):
        try container.encode(value, forKey: .destNodeGroup)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specifies the source criteria for this edge rule.
  /// An edge rule must define its source either statically via a specific
  /// node type, or dynamically via a group of nodes that match given
  /// constraints.
  ///
  /// This takes precedence over the `source_node_type` field.
  public enum OneOf_SourceNode: Codable, Equatable, Sendable {
    /// Optional. The specific node type name that acts as the source for this
    /// edge.
    case srcNodeType(Swift.String)
    /// Optional. A dynamic group of nodes, defined by label constraints, that
    /// can act as the source for this edge.
    indirect case srcNodeGroup(NodeGroup?)
  }

  /// Specifies the destination criteria for this edge rule.
  /// An edge rule must define its destination either statically via a specific
  /// node type, or dynamically via a group of nodes that match given
  /// constraints.
  ///
  /// This takes precedence over the `destination_node_type` field.
  public enum OneOf_DestinationNode: Codable, Equatable, Sendable {
    /// Optional. The specific node type name that acts as the destination for
    /// this edge.
    case destNodeType(Swift.String)
    /// Optional. A dynamic group of nodes, defined by label constraints, that
    /// can act as the destination for this edge.
    indirect case destNodeGroup(NodeGroup?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apptopology.v1.EdgeRule"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
