// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// EdgeType defines the schema of an edge type in the graph.
public struct EdgeType: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// REQUIRED
  /// Name of the edge type.
  /// This name is used to access the edge type while defining the schema.
  public var type: Swift.String = Swift.String()

  /// Labels attached to the edge. Composable, namespaced building blocks that
  /// define core attributes through associated properties. Multiple labels
  /// aggregate to fully specify the functional traits and property schema of the
  /// edge type.
  public var labels: [Swift.String] = []

  /// A human-readable description of the `EdgeType`.
  public var description: Swift.String = Swift.String()

  /// An edge of this edge type can have 0 or more of these labels. These edge
  /// objects of this edge type will have these labels alongside the
  /// required labels.
  public var optionalLabels: [Swift.String] = []

  /// Initialize a new instance of `EdgeType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EdgeType().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apptopology.v1.EdgeType"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
