// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for ExploreSchema.
public struct ExploreSchemaRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the singleton domain schema resource.
  /// Format: `projects/{project}/locations/{location}/domains/{domain}/schema`
  public var name: Swift.String = Swift.String()

  /// Optional. Starting label names to begin traversal.
  /// Substring, case-insensitive matches are performed against allowed label
  /// names in the schema. A maximum of 10 `start_labels` can be specified;
  /// providing more will result in an `INVALID_ARGUMENT` error.
  /// If `start_labels` is unset or empty, all authorized node types will be used
  /// as the starting set.
  public var startLabels: [Swift.String] = []

  /// Optional. The maximum depth of BFS traversal hops to perform from the
  /// starting node types or label names. Defaults to 0 if unspecified.
  public var depth: Swift.Int32 = Swift.Int32()

  /// Optional. The maximum number of schema elements to return in a single page.
  ///
  /// - The service might return fewer elements than this value if adding another
  ///   edge and its required endpoint nodes exceeds `page_size`.
  /// - If omitted or set to 0, default (100) will be used.
  /// - Minimum page_size is 3 to ensure at least one edge and its endpoint
  ///   nodes fit on a page; values below 3 (e.g. 1 or 2) are changed to 3.
  /// - Maximum value is 500.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token received from a previous `ExploreSchema` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters (except page_size) provided to
  /// `ExploreSchema` must match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExploreSchemaRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExploreSchemaRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let startLabels = CodingKeys(stringValue: "startLabels")
    static let depth = CodingKeys(stringValue: "depth")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "startLabels",
      "depth",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .startLabels) {
      self.startLabels = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .depth) {
      self.depth = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.startLabels, forKey: .startLabels)
    try container.encode(self.depth, forKey: .depth)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ExploreSchemaRequest`: `"type.googleapis.com/google.cloud.apptopology.v1.ExploreSchemaRequest"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apptopology.v1.ExploreSchemaRequest"
  }

  /// Initialize an instance of `ExploreSchemaRequest` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.apptopology.v1.ExploreSchemaRequest"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ExploreSchemaRequest` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
