// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for GenerateDiscoveredResourcesTopology.
public struct GenerateDiscoveredResourcesTopologyRequest: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The project to query discoverable resources on.
  /// Expected format:
  /// `projects/{project}/locations/{location}/discoveredResourcesTopology`.
  /// Only `global` location is supported.
  public var name: Swift.String = Swift.String()

  /// Required. The full resource name of the domain of the app topology.
  /// Format: `projects/{project}/locations/{location}/domains/{domain}`
  /// Caller must have apptopology.domains.get permission on each of the domains.
  public var topologyDomains: [Swift.String] = []

  /// Query the topology by building a graph pattern filter or pre-defined
  /// topology view.
  public var query: OneOf_Query? = nil

  /// Initialize a new instance of `GenerateDiscoveredResourcesTopologyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateDiscoveredResourcesTopologyRequest().with { $0.filter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case filter = "filter"
    case name = "name"
    case topologyDomains = "topologyDomains"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.topologyDomains = try container.decode([Swift.String].self, forKey: .topologyDomains)

    var query: OneOf_Query? = nil
    let queryCheckAndSet = {
      if query != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'query'"))
      }
      query = $0
    }
    if let filter = try container.decodeIfPresent(GraphPattern?.self, forKey: .filter) {
      try queryCheckAndSet(.filter(filter))
    }
    self.query = query
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.topologyDomains, forKey: .topologyDomains)

    if let choice = self.query {
      switch choice {
      case .filter(let value):
        try container.encode(value, forKey: .filter)
      }
    }
  }

  /// Query the topology by building a graph pattern filter or pre-defined
  /// topology view.
  public enum OneOf_Query: Codable, Equatable, Sendable {
    /// Filters for the topology nodes and edges; Detail format see GraphPattern
    /// proto. A separate 'LookupSchema' method will be added that will return
    /// the necessary information to be able to construct these filters.
    indirect case filter(GraphPattern?)
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.apptopology.v1.GenerateDiscoveredResourcesTopologyRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
