// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Recursive graph pattern matcher to select and constrain the returned
/// topology.
/// AppTopology API allows cycle in the graph traversal and will return unique
/// node and edge results in the response.
/// SLO is guaranteed for at most 5 hops in the graph traversal.
public struct GraphPattern: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Pattern matcher to select the starting nodes in the graph.
  public var startingNode: NodePattern? = nil

  /// Optional. Pattern matcher to match the connected subgraphs; all of these
  /// are ANDed.
  public var neighbors: [ConnectedNodePattern] = []

  /// Initialize a new instance of `GraphPattern`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GraphPattern().with { $0.startingNode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apptopology.v1.GraphPattern"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
