// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents a single node in the graph.
public struct Node: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Properties associated with the node.
  /// Refer to https://apptopology.googleapis.com/v1/GetSchema for a detailed
  /// list of node properties.
  public var properties: GoogleCloudWKT.Struct? = nil

  /// The global unique name of the node.
  /// For standard Google Cloud Platform resources, this MUST be the canonical
  /// Full Resource Name.
  ///
  /// Examples:
  ///
  /// - type: compute.googleapis.com/Instance
  ///   name:
  ///   "//compute.googleapis.com/projects/my-project-id/zones/us-central1-a/instances/my-vm-1"
  ///
  /// - type: container.googleapis.com/Cluster
  ///   name:
  ///   "//container.googleapis.com/projects/my-project-id/locations/us-central1/clusters/my-cluster"
  public var name: Swift.String = Swift.String()

  /// Labels attached to the node. Composable, namespaced building blocks that
  /// define core attributes through associated properties. Multiple labels
  /// aggregate to fully specify the functional traits and property schema of the
  /// node type.
  public var labels: [Swift.String] = []

  /// The context of the node.
  public var context: EntityContext? = nil

  /// Initialize a new instance of `Node`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Node().with { $0.properties = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apptopology.v1.Node"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
