// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Property defines the schema of a property in the graph.
public struct Property: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// `name` is the key string to identify the property in `Node`s & `Edge`s.
  /// Examples: `ProjectId`, `Base/displayName` etc.
  public var name: Swift.String = Swift.String()

  /// A human-readable description of the `PropertyType`, explaining its meaning,
  /// purpose, and any constraints or expectations on its value.
  public var description: Swift.String = Swift.String()

  /// REQUIRED
  /// Value type of the property.
  public var value: OneOf_Value? = nil

  /// Initialize a new instance of `Property`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Property().with { $0.stringValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case stringValue = "stringValue"
    case intValue = "intValue"
    case boolValue = "boolValue"
    case doubleValue = "doubleValue"
    case name = "name"
    case description = "description"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.description = try container.decode(Swift.String.self, forKey: .description)

    var value: OneOf_Value? = nil
    let valueCheckAndSet = {
      if value != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'value'"))
      }
      value = $0
    }
    if let stringValue = try container.decodeIfPresent(StringValue?.self, forKey: .stringValue) {
      try valueCheckAndSet(.stringValue(stringValue))
    }
    if let intValue = try container.decodeIfPresent(IntValue?.self, forKey: .intValue) {
      try valueCheckAndSet(.intValue(intValue))
    }
    if let boolValue = try container.decodeIfPresent(BoolValue?.self, forKey: .boolValue) {
      try valueCheckAndSet(.boolValue(boolValue))
    }
    if let doubleValue = try container.decodeIfPresent(DoubleValue?.self, forKey: .doubleValue) {
      try valueCheckAndSet(.doubleValue(doubleValue))
    }
    self.value = value
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)

    if let choice = self.value {
      switch choice {
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .intValue(let value):
        try container.encode(value, forKey: .intValue)
      case .boolValue(let value):
        try container.encode(value, forKey: .boolValue)
      case .doubleValue(let value):
        try container.encode(value, forKey: .doubleValue)
      }
    }
  }

  /// REQUIRED
  /// Value type of the property.
  public enum OneOf_Value: Codable, Equatable, Sendable {
    /// StringValue represents a property that has a string value type.
    indirect case stringValue(StringValue?)
    /// IntValue represents a property that has an integer value type.
    indirect case intValue(IntValue?)
    /// BoolValue represents a property that has a boolean value type.
    indirect case boolValue(BoolValue?)
    /// DoubleValue represents a property that has a double value type.
    indirect case doubleValue(DoubleValue?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.apptopology.v1.Property"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
